[package]
name = "binomial-heap"
version = "0.1.0"
edition = "2021"
authors = ["Alexandre Lamarre <alex7285@gmail.com>"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
