/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alproburoro;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.NumberFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nadila
 */
public class MainClass extends javax.swing.JFrame {

    public int jumlahData = 0;
    private String[][] temp;
    //GetSet getSet;
    data data2;

    double BodyMassIndex;
    double tinggi;
    double berat, kaloriPerHari1, KaloriPerHari2, kar, fat, pro;
    int usia, urut;
    String gender, nama, goal, aktivitas;

    //batas indeks awal dan akhir berat ideal perempuan
    int BatasAwalIdealPr = 18;
    int BatasAkhirIdealPr = 25;

    //batas obesitas laki-laki maupun perempuan
    int BatasObesitas = 27;

    //rumus batas awal dan akhir berat ideal perempuan
    double BeratIdealPr1 = BatasAwalIdealPr * (Math.pow(tinggi, 2));
    int BeratIdealPR1 = (int) BeratIdealPr1;
    double BeratIdealPr2 = BatasAkhirIdealPr * Math.pow(tinggi, 2);
    int BeratIdealPR2 = (int) BeratIdealPr2;

    //Batas indek awal dan akhir berat ideal laki-laki
    int BatasAwalIdealLk = 17;
    int BatasAkhirIdealLk = 23;

    //rumus batas awal dan akhir berat ideal laki-laki
    double BeratIdealLk1 = BatasAwalIdealLk * Math.pow(tinggi, 2);
    int BeratIdealLK1 = (int) BeratIdealLk1;
    double BeratIdealLk2 = BatasAkhirIdealLk * Math.pow(tinggi, 2);
    int BeratIdealLK2 = (int) BeratIdealLk2;

    /**
     * Creates new form tabel
     */
    public MainClass() {
        //this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        //this.setUndecorated(true);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();

        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(1020, 720);
        urut = 1;

        data2 = new data(100);
        tableModel2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGender = new javax.swing.ButtonGroup();
        ButtonGoal = new javax.swing.ButtonGroup();
        ButtonAktivitas = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jberat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtinggi = new javax.swing.JTextField();
        jusia = new javax.swing.JTextField();
        jnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bBMI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bKalori = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();
        lblBMI = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        radioLK = new javax.swing.JRadioButton();
        radioPR = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jKalori = new javax.swing.JLabel();
        jKarbohidrat = new javax.swing.JLabel();
        jLemak = new javax.swing.JLabel();
        jProtein = new javax.swing.JLabel();
        goal1 = new javax.swing.JRadioButton();
        goal2 = new javax.swing.JRadioButton();
        goal3 = new javax.swing.JRadioButton();
        aktivitas1 = new javax.swing.JRadioButton();
        aktivitas2 = new javax.swing.JRadioButton();
        aktivitas3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Berat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 120, 60, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Usia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 182, 70, 15);

        jberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jberatActionPerformed(evt);
            }
        });
        getContentPane().add(jberat);
        jberat.setBounds(105, 117, 380, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Aktivitas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 120, 70, 15);

        jtinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggiActionPerformed(evt);
            }
        });
        getContentPane().add(jtinggi);
        jtinggi.setBounds(105, 148, 380, 30);

        jusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusiaActionPerformed(evt);
            }
        });
        getContentPane().add(jusia);
        jusia.setBounds(105, 179, 380, 30);

        jnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnamaActionPerformed(evt);
            }
        });
        getContentPane().add(jnama);
        jnama.setBounds(105, 61, 380, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BERAT BADAN IDEAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(434, 11, 220, 30);

        bBMI.setBackground(new java.awt.Color(0, 153, 102));
        bBMI.setForeground(new java.awt.Color(51, 51, 51));
        bBMI.setText("BodyMassIndex");
        bBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBMIActionPerformed(evt);
            }
        });
        getContentPane().add(bBMI);
        bBMI.setBounds(168, 211, 170, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 64, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 93, 60, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Goal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 93, 70, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 151, 60, 15);

        bKalori.setBackground(new java.awt.Color(0, 153, 102));
        bKalori.setForeground(new java.awt.Color(51, 51, 51));
        bKalori.setText("Hitung Kalori Per Hari");
        bKalori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKaloriActionPerformed(evt);
            }
        });
        getContentPane().add(bKalori);
        bKalori.setBounds(726, 211, 180, 23);

        jlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlabel.setText("BMI");
        getContentPane().add(jlabel);
        jlabel.setBounds(520, 64, 70, 15);

        lblBMI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBMI.setText("0");
        getContentPane().add(lblBMI);
        lblBMI.setBounds(588, 64, 80, 15);

        jStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jStatus.setText("-");
        getContentPane().add(jStatus);
        jStatus.setBounds(691, 59, 320, 25);

        ButtonGender.add(radioLK);
        radioLK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioLK.setText("Male");
        getContentPane().add(radioLK);
        radioLK.setBounds(110, 90, 90, 23);

        ButtonGender.add(radioPR);
        radioPR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioPR.setText("Female");
        radioPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPRActionPerformed(evt);
            }
        });
        getContentPane().add(radioPR);
        radioPR.setBounds(205, 89, 90, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Kalori per Hari");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(575, 245, 100, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Karbohidrat");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(596, 265, 90, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Lemak");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(596, 285, 80, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Protein");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(596, 309, 80, 15);

        jKalori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jKalori.setText("0");
        getContentPane().add(jKalori);
        jKalori.setBounds(688, 245, 180, 15);

        jKarbohidrat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jKarbohidrat.setText("0");
        getContentPane().add(jKarbohidrat);
        jKarbohidrat.setBounds(701, 265, 90, 15);

        jLemak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLemak.setText("0");
        getContentPane().add(jLemak);
        jLemak.setBounds(701, 285, 40, 15);

        jProtein.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jProtein.setText("0");
        getContentPane().add(jProtein);
        jProtein.setBounds(701, 309, 50, 15);

        ButtonGoal.add(goal1);
        goal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goal1.setText("Weight Loss");
        getContentPane().add(goal1);
        goal1.setBounds(589, 89, 120, 23);

        ButtonGoal.add(goal2);
        goal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goal2.setText("Maintain Current Weight");
        getContentPane().add(goal2);
        goal2.setBounds(710, 90, 200, 23);

        ButtonGoal.add(goal3);
        goal3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goal3.setText("Weight Gain");
        getContentPane().add(goal3);
        goal3.setBounds(910, 90, 100, 23);

        ButtonAktivitas.add(aktivitas1);
        aktivitas1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aktivitas1.setText("Sedentary");
        getContentPane().add(aktivitas1);
        aktivitas1.setBounds(589, 116, 110, 23);

        ButtonAktivitas.add(aktivitas2);
        aktivitas2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aktivitas2.setText("Mode Active");
        getContentPane().add(aktivitas2);
        aktivitas2.setBounds(589, 147, 130, 23);

        ButtonAktivitas.add(aktivitas3);
        aktivitas3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aktivitas3.setText("Active ");
        getContentPane().add(aktivitas3);
        aktivitas3.setBounds(589, 178, 80, 23);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 310, 90, 23);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 310, 100, 23);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 310, 110, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText(" (Ch: pegawai, pekerja kantoran)");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(700, 120, 240, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText(" (Ch: ibu rumah tangga, tukang)");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(720, 150, 270, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("(Ch: Atlet)");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(680, 180, 190, 14);

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Sort Insertion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 310, 140, 23);

        jButton5.setBackground(new java.awt.Color(204, 0, 51));
        jButton5.setText("KEMBALI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 310, 80, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alproburoro/a.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -330, 1020, 670);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Gender", "Berat", "Tinggi", "Usia", "BMI", "Goal", "aktivitas", "KaloriPerHari", "Karbohidrat", "Lemak", "Protein"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 340, 1020, 402);

        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 250, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnamaActionPerformed
        JTextField nama = new JTextField();
    }//GEN-LAST:event_jnamaActionPerformed

    private void bBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBMIActionPerformed

        jLabel17.setText(Integer.toString(urut));
        berat = Double.parseDouble(jberat.getText());
        tinggi = Double.parseDouble(jtinggi.getText());
        tinggi = tinggi / 100;
        BodyMassIndex = berat / (Math.pow(tinggi, 2));
        lblBMI.setText(Double.toString((int) BodyMassIndex));
        if (radioPR.isSelected()) {
            if (BodyMassIndex < BatasAwalIdealPr) {
                jStatus.setText("Anda kekurangan berat badan");
            } else if (BodyMassIndex > BatasAwalIdealPr && BodyMassIndex < BatasAkhirIdealPr) {
                jStatus.setText("Selamat! Berat badan Anda ideal");
            } else if (BodyMassIndex > BatasAkhirIdealPr && BodyMassIndex < BatasObesitas) {
                jStatus.setText("Anda kelebihan berat badan");
            }
        } else if (radioLK.isSelected()) {
            if (BodyMassIndex < BatasAwalIdealLk) {
                jStatus.setText("Anda kekurangan berat badan");
            } else if (BodyMassIndex > BatasAwalIdealLk && BodyMassIndex < BatasAkhirIdealLk) {
                jStatus.setText("Selamat! Berat badan Anda ideal");
            } else if (BodyMassIndex > BatasAkhirIdealLk && BodyMassIndex < BatasObesitas) {
                jStatus.setText("Anda kelebihan berat badan");
            }
        }


    }//GEN-LAST:event_bBMIActionPerformed

    private void bKaloriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKaloriActionPerformed

        //berat = Double.parseDouble(jberat.getText());
        tinggi = Double.parseDouble(jtinggi.getText());
        usia = Integer.parseInt(jusia.getText());
        if (goal1.isSelected() && radioPR.isSelected()) {
            if (aktivitas1.isSelected()) {
                kaloriPerHari1 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.2) * 80 / 100;
                KaloriPerHari2 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.3;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma

                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas2.isSelected()) {
                kaloriPerHari1 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.3) * 80 / 100;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                jLemak.setText(Double.toString(lemak));
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas3.isSelected()) {
                kaloriPerHari1 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.4) * 80 / 100;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            }
        } else if (goal1.isSelected() && radioLK.isSelected()) {
            if (aktivitas1.isSelected()) {
                KaloriPerHari2 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.2) * 80 / 100;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas2.isSelected()) {
                KaloriPerHari2 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.3) * 80 / 100;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas3.isSelected()) {
                KaloriPerHari2 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.4) * 80 / 100;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            }
        } else if (goal2.isSelected() && radioPR.isSelected()) {
            if (aktivitas1.isSelected()) {
                kaloriPerHari1 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.2;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas2.isSelected()) {
                kaloriPerHari1 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.3;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas3.isSelected()) {
                kaloriPerHari1 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.4;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            }
        } else if (goal2.isSelected() && radioLK.isSelected()) {
            if (aktivitas1.isSelected()) {
                KaloriPerHari2 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.2;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas2.isSelected()) {
                KaloriPerHari2 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.3;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas3.isSelected()) {
                KaloriPerHari2 = ((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.4;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            }
        } else if (goal3.isSelected() && radioPR.isSelected()) {
            if (aktivitas1.isSelected()) {
                kaloriPerHari1 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.2) * 120 / 100;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas2.isSelected()) {
                kaloriPerHari1 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.3) * 120 / 100;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas3.isSelected()) {
                kaloriPerHari1 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) - 161) * 1.4) * 120 / 100;
                kar = kaloriPerHari1 * 55 / 100;
                int karbohidrat = (int) kar; //Mengubah int menjadi double agar output tidak koma
                fat = kaloriPerHari1 * 30 / 100;
                int lemak = (int) fat; //Mengubah int menjadi double agar output tidak koma
                pro = kaloriPerHari1 * 15 / 100;
                int protein = (int) pro; //Mengubah int menjadi double agar output tidak koma
                jKalori.setText(Double.toString(kaloriPerHari1));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            }

        } else if (goal3.isSelected() && radioLK.isSelected()) {
            if (aktivitas1.isSelected()) {
                KaloriPerHari2 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.2) * 120 / 100;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar;
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat;
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro;
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas2.isSelected()) {
                KaloriPerHari2 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.3) * 120 / 100;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar;
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat;
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro;
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            } else if (aktivitas3.isSelected()) {
                KaloriPerHari2 = (((10 * berat) + (6.25 * tinggi) - (5 * usia) + 5) * 1.4) * 120 / 100;
                kar = KaloriPerHari2 * 55 / 100;
                int karbohidrat = (int) kar;
                fat = KaloriPerHari2 * 30 / 100;
                int lemak = (int) fat;
                pro = KaloriPerHari2 * 15 / 100;
                int protein = (int) pro;
                jKalori.setText(Double.toString(KaloriPerHari2));
                jKarbohidrat.setText(Double.toString(karbohidrat));
                jLemak.setText(Double.toString(lemak));
                jProtein.setText(Double.toString(protein));
            }
        }

    }//GEN-LAST:event_bKaloriActionPerformed

    private void jberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jberatActionPerformed
        JTextField berat = new JTextField();
    }//GEN-LAST:event_jberatActionPerformed

    private void jtinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggiActionPerformed
        JTextField tinggi = new JTextField();
    }//GEN-LAST:event_jtinggiActionPerformed

    private void jusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusiaActionPerformed
        JTextField usia = new JTextField();
    }//GEN-LAST:event_jusiaActionPerformed

    private void radioPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        urut = Integer.parseInt(jLabel17.getText());
        urut++;
        nama = jnama.getText();
        if (radioPR.isSelected()) {
            gender = radioPR.getText();
        } else if (radioLK.isSelected()) {
            gender = radioLK.getText();
        }
        berat = Double.parseDouble(jberat.getText());
        tinggi = Double.parseDouble(jtinggi.getText());
        usia = Integer.parseInt(jusia.getText());
        BodyMassIndex = Double.parseDouble(lblBMI.getText());
        if (goal1.isSelected()) {
            goal = goal1.getText();
        } else if (goal2.isSelected()) {
            goal = goal2.getText();
        } else if (goal3.isSelected()) {
            goal = goal3.getText();
        }
        if (aktivitas1.isSelected()) {
            aktivitas = aktivitas1.getText();
        } else if (aktivitas2.isSelected()) {
            aktivitas = aktivitas2.getText();
        } else if (aktivitas3.isSelected()) {
            aktivitas = aktivitas3.getText();
        }
        kaloriPerHari1 = Double.parseDouble(jKalori.getText());
        kar = Double.parseDouble(jKarbohidrat.getText());
        fat = Double.parseDouble(jLemak.getText());
        pro = Double.parseDouble(jProtein.getText());
        data2.insert(urut, nama, gender, berat, tinggi, usia, BodyMassIndex, goal, aktivitas, kaloriPerHari1, kar, fat, pro);

//        try {
//            String sql = "INSERT INTO dietsehat VALUES ('"+urut+","+nama+"','"+gender+"','"+(int)berat+"','"+(int)tinggi+"','"+usia+"','"+(int)BodyMassIndex+"','"+goal+","+aktivitas+","+(int)kaloriPerHari1+","+(int)kar+","+(int)fat+","+(int)pro+"')";
//            java.sql.Connection conn=(Connection)config.configDB();
//            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
//            pst.execute();
//            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
        database();
        tableModel2();
        
        reset();


    }//GEN-LAST:event_jButton1ActionPerformed
    public void tableModel2() {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);
        String[][] res = data2.readData();
        for (int i = 0; i < res.length; i++) {
            Object[] row = {res[i][0], res[i][1], res[i][2], res[i][3], res[i][4], res[i][5], res[i][6], res[i][7], res[i][8], res[i][9], res[i][10], res[i][11] };
            model.addRow(row);
        }
    }

    public void database() {
        connection k = new connection();
        k.getkoneksi();
        Connection conn = k.getkoneksi();
        PreparedStatement prepare;

        String sql = "insert into dietsehat values(?,?,?,?,?,?,?,?,?,?,?,?,?)";//jumlah tanda tanya adalah jumlah data yang akan dimunculkan di database
        try {
            prepare = conn.prepareStatement(sql); //agar dapat menghasilkan pernyataan yang telah disiapkan
            prepare.setInt(1, Integer.parseInt(jLabel17.getText()));
            prepare.setString(2, jnama.getText());
            prepare.setString(3, gender);
            prepare.setInt(4, (int) Integer.parseInt(jberat.getText()));
            prepare.setInt(5, (int) Integer.parseInt(jtinggi.getText())); //merubah double menjadi int
            prepare.setInt(6, Integer.parseInt(jusia.getText()));
            prepare.setInt(7, (int) BodyMassIndex);
            prepare.setString(8, aktivitas);
            prepare.setString(9, goal);
            prepare.setInt(10, (int) kaloriPerHari1);
            prepare.setInt(11, (int) kar); //merubah double menjadi int
            prepare.setInt(12, (int) fat); //merubah double menjadi int
            prepare.setInt(13, (int) pro); //merubah double menjadi int
            prepare.executeUpdate(); //untuk meng-update data yang ada didatabase, agar ketika kita menginput data baru database akan menambahkan data yang sudah ada
            prepare.close(); //untuk menutup statement agar tidak tertumpuk dengan statement lain. jika tidak diclose maka statement akan terus berjalan
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void copy() {

    }

    public void insertionsort() {
        data2.insertionsort();
    }

    public void insertionsortumur() {
        data2.insertionsortumur();
    }

    public void selectionsort2() {
        data2.selectionsort2();
    }

    public void bubblesort() {
        data2.bubblesort();
    }

    public void insertion() {
        data2.insertion();
    }

    public void selectionSort() {
        data2.SelectionSort();
    }

    public void urutan() {
        data2.methodbantuan();
    }

    public void insertdatatoarray() {
        data2.readData();
    }

    public void bubblesort2() {
        data2.Bubblesort2();
    }

    public void reset() {
        jnama.setText("");
        jberat.setText("");
        jtinggi.setText("");
        jusia.setText("");
        lblBMI.setText("0");
        jStatus.setText("-");
        jKalori.setText("0");
        jKarbohidrat.setText("0");
        jLemak.setText("0");
        jProtein.setText("0");
        ButtonGender.clearSelection();
        ButtonGoal.clearSelection();
        ButtonAktivitas.clearSelection();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insertdatatoarray();
        urutan();
        tableModel2();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        insertdatatoarray();
        bubblesort();
        tableModel2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        insertdatatoarray();
        insertionsort();
        tableModel2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Mulai frame = new Mulai();
        frame.setVisible(true);
        this.dispose();
//    database();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        int baris = jTable.rowAtPoint(evt.getPoint());
        int urut = Integer.parseInt(jTable.getValueAt(baris, 1).toString());
        //jLabel17.setText();
    }//GEN-LAST:event_jTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonAktivitas;
    private javax.swing.ButtonGroup ButtonGender;
    private javax.swing.ButtonGroup ButtonGoal;
    private javax.swing.JRadioButton aktivitas1;
    private javax.swing.JRadioButton aktivitas2;
    private javax.swing.JRadioButton aktivitas3;
    private javax.swing.JButton bBMI;
    private javax.swing.JButton bKalori;
    private javax.swing.JRadioButton goal1;
    private javax.swing.JRadioButton goal2;
    private javax.swing.JRadioButton goal3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jKalori;
    private javax.swing.JLabel jKarbohidrat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLemak;
    private javax.swing.JLabel jProtein;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jStatus;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jberat;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jtinggi;
    private javax.swing.JTextField jusia;
    private javax.swing.JLabel lblBMI;
    private javax.swing.JRadioButton radioLK;
    private javax.swing.JRadioButton radioPR;
    // End of variables declaration//GEN-END:variables
}
